#!/bin/sh
LANG=en_US.utf8
LC_ALL=en_US.utf8

if \
   [ -f /etc/portage/package.oldcc ] && \
   { read -r MY_OLDCC < /etc/portage/oldcc; } 2>/dev/null && \
   [ -n "${MY_OLDCC}" ]
then
   # command() 'escapes' QA check
   if command grep -Fxq -- "${CATEGORY}/${PN}" \
      /etc/portage/package.oldcc
   then
      export ROOTPATH="${MY_OLDCC}${ROOTPATH:+:${ROOTPATH}}"
      export PATH="${MY_OLDCC}${PATH:+:${PATH}}"
      export LIBRARY_PATH="${MY_OLDCC}${LIBRARY_PATH:+:${LIBRARY_PATH}}"
   fi
fi
