override FIMKLIB_BUILDSCRIPTS := $(FIMKLIB_ROOT)/build-scripts

X_FIND_SHFILES      = $(PYTHON_PREFER3) $(FIMKLIB_BUILDSCRIPTS)/find-shell-script-files
X_EXTRACT_HASHBANG  = $(AWKF) $(FIMKLIB_BUILDSCRIPTS)/extract-hashbang
X_SHELLCHECK        = $(SHELL) $(FIMKLIB_BUILDSCRIPTS)/run-shellcheck
X_METASH            = $(PYTHON_PREFER3) $(FIMKLIB_BUILDSCRIPTS)/metash
X_METASH_MULTI      = $(SHELL) $(FIMKLIB_BUILDSCRIPTS)/run-metash
X_MERGE_SCRIPTFILES = $(PYTHON_PREFER3) $(FIMKLIB_BUILDSCRIPTS)/merge-scriptfiles
