#!/bin/sh
# "Hardwired" screen wrapper. See also "screen-attach-or-run".
#
# Note: "sh -c CODE [ARG0 [ARG...]]" -- need to specify a prog name (ARG0)
#
set -u

: "${X_SCREEN:=screen}"
: "${X_IRSSI:=irssi}"
IRSSI_ARGS=

session_name="irssi-session"

while [ ${#} -gt 0 ]; do
   case "${1}" in
      '')
         exit 64
      ;;
      --fg)
         SCREEN_REATTACH_ONLY=y
      ;;
      --bg|--init|init|--fixup)
         SCREEN_IN_BG=y
      ;;
      *)
         break
      ;;
   esac
   shift || exit
done

list_screen_sessions() {
"${X_SCREEN}" -ls | \
awk -v name="${1:-.+}" \
'( ($0 ~ "^\\s") && ($1 ~ ("^[0-9]+[.]" name "$")) ) { print $1; }'
}


# attach to existing session or create a new one
session="$( list_screen_sessions "${session_name}" | head -n 1 )"

set -- "${X_IRSSI}" ${IRSSI_ARGS}

if [ -n "${session}" ]; then
   [ "${SCREEN_IN_BG:-X}" != "y" ] || exit 0
   exec "${X_SCREEN}" -d -r -S "${session}"

elif [ "${SCREEN_REATTACH_ONLY:-X}" = "y" ]; then
   exit 1

elif [ "${SCREEN_IN_BG:-X}" = "y" ]; then
   exec "${X_SCREEN}" -d -m -S "${session_name}" -- "${@}"

else
   exec "${X_SCREEN}" -S "${session_name}" -- "${@}"
fi
